### ISSUE TITLE
[Question] Does it able to read/write system preferences?

### ISSUE THREAD

**Issue by dkfiresky** [Jense5/node-user-defaults#8]
Does this module able to read/write files in '~/Library/Preferences'?
Example:
```sh
$ defaults read -g AppleAquaColorVariant
1

$ defaults read -g AppleInterfaceStyle
Dark
```

Or this module is "a replica" kind of NSUserDefaults?

**Comment by Jense5** [comment]
No, this module is just to store preferences of an application. This means it is "a replica" kind of NSUserDefaults.

**Comment by dkfiresky** [comment]
@Jense5, thanks.
